### ISSUE TITLE
Traceback 

### ISSUE THREAD

**Issue by aosinda** [C3n7ral051nt4g3ncy/Prot1ntelligence#1]
Hi

Thank you for the script! I am getting a traceback on module B all the time: 

 raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests

**Comment by C3n7ral051nt4g3ncy** [comment]
Hi there! 

Was it working previously? if yes, the HTTP error 429 is the server basically asking you to stop as many requests. It usually means the number of requests has been a little high and the server can't accept as many requests.

**Comment by aosinda** [comment]
That's the/my issue - it gave me the traceback the first time I ran it.

**Comment by C3n7ral051nt4g3ncy** [comment]
> That's the/my issue - it gave me the traceback the first time I ran it.

Just checked again, **everything is good with the script**. 
 @aosinda, did you run `pip3 install -r requirements.txt`
